In [6]:
import pandas as pd
import numpy as np
ball_by_ball = pd.read_csv('../resources/train/ball_by_ball_data.csv')
match_data = pd.read_csv('../resources/train/match_data.csv')
bbb_venue = ball_by_ball.merge(match_data, on='match_id')
bbb_venue.head(n=2)
mbm = ball_by_ball[ball_by_ball['extra_runs'] == 0].groupby(['match_id', 'inning', 'batting_team', 'bowling_team', 
                            'batsman_id']).agg({'batsman_runs': np.sum, 'bowler_id': np.size}).rename(columns={'bowler_id':'deliveries'}).reset_index()
mbm_venue = mbm.merge(match_data, on='match_id')

In [7]:

bat_sat = bbb_venue[['batsman_id', 'match_id', 'season', 'bowling_team', 'venue_id', 'batsman_runs']]

bat_sat_agg = bbb_venue.groupby(['batsman_id', 'season', 'bowling_team', 'venue_id']).agg({'batsman_runs': np.sum}).reset_index()
bat_sat_agg.head(n=2)

   batsman_id  season bowling_team  venue_id  batsman_runs
0           1    2008           DC         4            37
1           1    2008           DC         5            23

In [8]:
bat_run_group = bbb_venue[bbb_venue['extra_runs'] == 0].groupby(['batsman_id', 'season', 'bowling_team', 'venue_id', 'batsman_runs']).agg({'match_id': np.size}).reset_index()
bat_run_group.head(n = 10)

   batsman_id  season bowling_team  venue_id  batsman_runs  match_id
0           1    2008           DC         4             0         7
1           1    2008           DC         4             1         9
2           1    2008           DC         4             2         3
3           1    2008           DC         4             4         4
4           1    2008           DC         4             6         1
5           1    2008           DC         5             0        18
6           1    2008           DC         5             1         7
7           1    2008           DC         5             2         4
8           1    2008           DC         5             4         2
9           1    2008           DD         2             0        10

In [9]:
for i in [0,1,2,3,4,6]:
    cname = str(i) + "_runs"
    bat_run_group[cname] = bat_run_group.apply(lambda x: x.match_id if x.batsman_runs == i else 0, axis = 1)
    
bat_run_group.head(n=10)

,batsman_id,season,bowling_team,venue_id,batsman_runs,match_id,0_runs,1_runs,2_runs,3_runs,4_runs,6_runs
0,1,2008,DC,4,0,7,7,0,0,0,0,0
1,1,2008,DC,4,1,9,0,9,0,0,0,0
2,1,2008,DC,4,2,3,0,0,3,0,0,0
3,1,2008,DC,4,4,4,0,0,0,0,4,0
4,1,2008,DC,4,6,1,0,0,0,0,0,1
5,1,2008,DC,5,0,18,18,0,0,0,0,0
6,1,2008,DC,5,1,7,0,7,0,0,0,0
7,1,2008,DC,5,2,4,0,0,4,0,0,0
8,1,2008,DC,5,4,2,0,0,0,0,2,0
9,1,2008,DD,2,0,10,10,0,0,0,0,0

In [10]:
bat_run_class = bat_run_group.groupby(['batsman_id', 'season', 'bowling_team', 'venue_id']).agg({'0_runs': np.sum, '1_runs': np.sum, '2_runs': np.sum, '3_runs': np.sum, '4_runs': np.sum, '6_runs': np.sum}).reset_index()
bat_run_class.head(n =10)

,batsman_id,season,bowling_team,venue_id,0_runs,1_runs,2_runs,3_runs,4_runs,6_runs
0,1,2008,DC,4,7,9,3,0,4,1
1,1,2008,DC,5,18,7,4,0,2,0
2,1,2008,DD,2,10,15,3,0,3,0
3,1,2008,DD,5,8,14,2,0,2,1
4,1,2008,KKR,5,6,13,3,0,3,2
5,1,2008,KXI,5,12,17,4,1,2,4
6,1,2008,KXI,9,1,2,0,0,0,0
7,1,2008,MI,1,14,11,1,0,6,1
8,1,2008,MI,5,4,4,2,0,4,1
9,1,2008,RCB,5,5,2,1,0,0,0

In [20]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
#dismissal_kind
dis_deliveries = bbb_venue[bbb_venue['player_dismissed_id'].notnull()][['match_id', 'player_dismissed_id', 'dismissal_kind']]

dis_sparse= mlb.fit_transform(dis_deliveries.apply(lambda x: set([x.dismissal_kind]), axis = 1))
dis_classes = list(mlb.classes_)

dis_del_byplayer = dis_deliveries.merge(pd.DataFrame(dis_sparse, columns = dis_classes, index = dis_deliveries.index), 
                     left_index=True, right_index=True)

mbm_venue['50s'] = mbm_venue.apply(lambda x: 1 if x.batsman_runs // 50 == 1 else 0,  axis = 1)
mbm_venue['100s'] = mbm_venue.apply(lambda x: 1 if x.batsman_runs // 50 > 1 else 0,  axis = 1)
mbm_stat = mbm_venue.merge(dis_del_byplayer, left_on=['batsman_id', 'match_id'], right_on=['player_dismissed_id', 'match_id'], 
                how='left')[['batsman_id', 'season', 'bowling_team', 'venue_id', 
                             'match_id', 'player_dismissed_id', 'deliveries', 'batsman_runs', '50s', '100s'] + dis_classes].fillna(0)

mbm_stat['is_dismissed'] = mbm_stat.apply(lambda x: 0 if x.player_dismissed_id==0 else 1, axis = 1)
mbm_stat['innings'] = mbm_stat.apply(lambda x : 1, axis = 1)
mbm_stat.head(n=2)

,batsman_id,season,bowling_team,venue_id,match_id,player_dismissed_id,deliveries,batsman_runs,50s,100s,...,caught,caught and bowled,hit wicket,lbw,obstructing the field,retired hurt,run out,stumped,is_dismissed,innings
0,66,2008,RCB,7,2008_1,66.0,10,10,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
1,73,2008,RCB,7,2008_1,73.0,19,20,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1

In [22]:
agg_dict = {x: np.sum for x in dis_classes + ['is_dismissed', 'innings', 'deliveries', 'batsman_runs', '50s', '100s']}
vbv_stat = mbm_stat.groupby(['batsman_id', 'season', 'bowling_team', 'venue_id']).agg(agg_dict ).reset_index()
vbv_stat.head(n=2)

,batsman_id,season,bowling_team,venue_id,bowled,caught,caught and bowled,hit wicket,lbw,obstructing the field,retired hurt,run out,stumped,is_dismissed,innings,deliveries,batsman_runs,50s,100s
0,1,2008,DC,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,24,37,0,0
1,1,2008,DC,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,31,23,0,0
2,1,2008,DD,2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,31,33,0,0
3,1,2008,DD,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,27,32,0,0
4,1,2008,KKR,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,27,43,0,0
5,1,2008,KXI,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,40,60,1,0
6,1,2008,KXI,9,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,3,2,0,0
7,1,2008,MI,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,33,43,0,0
8,1,2008,MI,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,15,30,0,0
9,1,2008,RCB,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,8,4,0,0
10,1,2008,RCB,7,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,30,65,1,0
11,1,2008,RR,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,8,12,0,0
12,1,2008,RR,6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,7,1,0,0
13,1,2008,RR,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,16,29,0,0
14,1,2009,DC,13,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,22,22,0,0
15,1,2009,DC,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,37,58,1,0
16,1,2009,DD,13,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,7,5,0,0
17,1,2009,DD,16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,7,6,0,0
18,1,2009,KKR,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,27,40,0,0
19,1,2009,KXI,13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,2,2,0,0
20,1,2009,KXI,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,27,56,1,0
21,1,2009,MI,11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,26,36,0,0
22,1,2009,MI,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,22,23,0,0
23,1,2009,RCB,12,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,14,16,0,0
24,1,2009,RCB,13,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,19,18,0,0
25,1,2009,RCB,16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,30,28,0,0
26,1,2009,RR,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,19,22,0,0
27,1,2010,DC,5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,29,42,0,0
28,1,2010,DC,10,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,30,30,0,0
29,1,2010,DC,22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,13,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,2013,KXI,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1,2,2,0,0
71,1,2013,MI,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,12,10,0,0
72,1,2013,MI,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,45,63,1,0
73,1,2013,MI,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,26,51,1,0
74,1,2013,PW,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,13,10,0,0
75,1,2013,PW,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,16,45,0,0
76,1,2013,RCB,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,22,32,0,0
77,1,2013,RCB,7,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,10,24,0,0
78,1,2013,RR,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,16,21,0,0
79,1,2013,RR,6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,3,2,0,0
80,1,2013,SRH,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,2,2,0,0
81,1,2013,SRH,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,36,67,1,0
82,1,2014,DD,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,5,12,0,0
83,1,2014,DD,29,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,14,32,0,0
84,1,2014,KKR,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,14,21,0,0
85,1,2014,KKR,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,14,22,0,0
86,1,2014,KXI,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,29,42,0,0
87,1,2014,KXI,21,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,20,23,0,0
88,1,2014,KXI,29,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,11,26,0,0
89,1,2014,MI,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,11,22,0,0
90,1,2014,MI,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,8,14,0,0
91,1,2014,RCB,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,27,49,0,0
92,1,2014,RCB,28,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,6,7,0,0
93,1,2014,RR,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,16,26,0,0
94,1,2014,RR,31,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,8,5,0,0
95,1,2014,SRH,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,39,57,1,0
96,1,2014,SRH,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,13,13,0,0
97,1,2015,DD,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,26,30,0,0
98,1,2015,DD,27,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,22,27,0,0
99,1,2015,KKR,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,4,1,0,0